---
title: "Rapeephan Duangjanchot"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Summary 

Rapeephan Duangjanchot completed bachelor’s (degree) program at the Department of Biotechnology, Faculty of Science, Mahidol University in 2019. Her senior project topic is ‘Markerless deletion of an enterotoxin gene cluster in *Bacillus cereus*. She currently studies at the Department of Medical bioinformatics, Faculty of Medicine Siriraj Hospital, Mahidol University. 

## Contact Info
109 village No.8, Thamaka Sub-district, Thamaka District, Kanchanaburi

## Social media profile
Medium: @rapeephannam

## Skills Summary 

### Scientific Software

- Attune NxT Flow Cytometer 
- SnapGene
- Minitab  

### Research skills 

- Aseptic techniques for cultivation of plant and microbial culture
- Molecular techniques (DNA isolation, primer design, PCR, plasmid construction, 
transformation and gel electrophoresis)
- Operation of bioprocessing units (e.g. bench-scale bioreactor, centrifuge, filter 
press, homogenizer, distillation and double-effect evaporator) 

## Experience

June 2020 – July 2020: Student internship, Hortigenetics research (S.E.Asia) limited

## Education

